# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 688)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Documents/logo_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_image.setGeometry(QtCore.QRect(60, 40, 381, 221))
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.lbl_mosaic = QtWidgets.QLabel(self.centralwidget)
        self.lbl_mosaic.setGeometry(QtCore.QRect(490, 60, 441, 441))
        self.lbl_mosaic.setAutoFillBackground(False)
        self.lbl_mosaic.setText("")
        self.lbl_mosaic.setObjectName("lbl_mosaic")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 290, 381, 311))
        self.widget.setObjectName("widget")
        self.frame_avance = QtWidgets.QFrame(self.widget)
        self.frame_avance.setGeometry(QtCore.QRect(10, 230, 361, 71))
        self.frame_avance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_avance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_avance.setObjectName("frame_avance")
        self.lbl_avance = QtWidgets.QLabel(self.frame_avance)
        self.lbl_avance.setGeometry(QtCore.QRect(130, 10, 81, 20))
        self.lbl_avance.setObjectName("lbl_avance")
        self.layoutWidget = QtWidgets.QWidget(self.frame_avance)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 311, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_avance = QtWidgets.QProgressBar(self.layoutWidget)
        self.pb_avance.setProperty("value", 0)
        self.pb_avance.setObjectName("pb_avance")
        self.horizontalLayout_3.addWidget(self.pb_avance)
        self.bt_lancer = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_lancer.setObjectName("bt_lancer")
        self.horizontalLayout_3.addWidget(self.bt_lancer)
        self.frame_button = QtWidgets.QFrame(self.widget)
        self.frame_button.setGeometry(QtCore.QRect(10, 10, 361, 80))
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.rb_rect = QtWidgets.QRadioButton(self.frame_button)
        self.rb_rect.setGeometry(QtCore.QRect(30, 10, 109, 25))
        self.rb_rect.setObjectName("rb_rect")
        self.rb_tri = QtWidgets.QRadioButton(self.frame_button)
        self.rb_tri.setGeometry(QtCore.QRect(190, 10, 109, 25))
        self.rb_tri.setObjectName("rb_tri")
        self.rb_hex = QtWidgets.QRadioButton(self.frame_button)
        self.rb_hex.setGeometry(QtCore.QRect(30, 40, 109, 25))
        self.rb_hex.setObjectName("rb_hex")
        self.rb_los = QtWidgets.QRadioButton(self.frame_button)
        self.rb_los.setGeometry(QtCore.QRect(190, 40, 109, 25))
        self.rb_los.setObjectName("rb_los")
        self.frame_verti = QtWidgets.QFrame(self.widget)
        self.frame_verti.setGeometry(QtCore.QRect(10, 161, 361, 71))
        self.frame_verti.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_verti.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_verti.setObjectName("frame_verti")
        self.lbl_subdiv_verti = QtWidgets.QLabel(self.frame_verti)
        self.lbl_subdiv_verti.setGeometry(QtCore.QRect(110, 10, 161, 21))
        self.lbl_subdiv_verti.setObjectName("lbl_subdiv_verti")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_verti)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 311, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hsld_subdiv_verti = QtWidgets.QSlider(self.layoutWidget1)
        self.hsld_subdiv_verti.setMinimum(2)
        self.hsld_subdiv_verti.setMaximum(100)
        self.hsld_subdiv_verti.setOrientation(QtCore.Qt.Horizontal)
        self.hsld_subdiv_verti.setObjectName("hsld_subdiv_verti")
        self.horizontalLayout_2.addWidget(self.hsld_subdiv_verti)
        self.sb_subdiv_verti = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sb_subdiv_verti.setMinimum(2)
        self.sb_subdiv_verti.setMaximum(100)
        self.sb_subdiv_verti.setObjectName("sb_subdiv_verti")
        self.horizontalLayout_2.addWidget(self.sb_subdiv_verti)
        self.lbl_subdiv_verti.raise_()
        self.layoutWidget.raise_()
        self.widget.raise_()
        self.frame_hori = QtWidgets.QFrame(self.widget)
        self.frame_hori.setEnabled(True)
        self.frame_hori.setGeometry(QtCore.QRect(10, 90, 361, 71))
        self.frame_hori.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hori.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hori.setObjectName("frame_hori")
        self.lbl_subdiv_hori = QtWidgets.QLabel(self.frame_hori)
        self.lbl_subdiv_hori.setGeometry(QtCore.QRect(110, 10, 161, 21))
        self.lbl_subdiv_hori.setObjectName("lbl_subdiv_hori")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_hori)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 30, 311, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hsld_subdiv_hori = QtWidgets.QSlider(self.layoutWidget2)
        self.hsld_subdiv_hori.setEnabled(True)
        self.hsld_subdiv_hori.setMinimum(2)
        self.hsld_subdiv_hori.setMaximum(100)
        self.hsld_subdiv_hori.setOrientation(QtCore.Qt.Horizontal)
        self.hsld_subdiv_hori.setObjectName("hsld_subdiv_hori")
        self.horizontalLayout.addWidget(self.hsld_subdiv_hori)
        self.sb_subdiv_hori = QtWidgets.QSpinBox(self.layoutWidget2)
        self.sb_subdiv_hori.setMinimum(2)
        self.sb_subdiv_hori.setMaximum(100)
        self.sb_subdiv_hori.setObjectName("sb_subdiv_hori")
        self.horizontalLayout.addWidget(self.sb_subdiv_hori)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(490, 540, 471, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_ouvrir = QtWidgets.QPushButton(self.frame)
        self.bt_ouvrir.setGeometry(QtCore.QRect(40, 10, 171, 28))
        self.bt_ouvrir.setObjectName("bt_ouvrir")
        self.bt_charger = QtWidgets.QPushButton(self.frame)
        self.bt_charger.setGeometry(QtCore.QRect(260, 10, 171, 28))
        self.bt_charger.setObjectName("bt_charger")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuBase_de_donn_e = QtWidgets.QMenu(self.menubar)
        self.menuBase_de_donn_e.setObjectName("menuBase_de_donn_e")
        self.menuA_propos = QtWidgets.QMenu(self.menubar)
        self.menuA_propos.setObjectName("menuA_propos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir_Image = QtWidgets.QAction(MainWindow)
        self.actionOuvrir_Image.setObjectName("actionOuvrir_Image")
        self.actionEnregistrer = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionEnregistrer_sous = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_sous.setObjectName("actionEnregistrer_sous")
        self.actionSelectionner_images = QtWidgets.QAction(MainWindow)
        self.actionSelectionner_images.setObjectName("actionSelectionner_images")
        self.actionActualiser = QtWidgets.QAction(MainWindow)
        self.actionActualiser.setObjectName("actionActualiser")
        self.actionLancer = QtWidgets.QAction(MainWindow)
        self.actionLancer.setObjectName("actionLancer")
        self.menuFichier.addAction(self.actionOuvrir_Image)
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionEnregistrer_sous)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionLancer)
        self.menuBase_de_donn_e.addAction(self.actionSelectionner_images)
        self.menuBase_de_donn_e.addAction(self.actionActualiser)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuBase_de_donn_e.menuAction())
        self.menubar.addAction(self.menuA_propos.menuAction())

        self.retranslateUi(MainWindow)
        self.hsld_subdiv_hori.valueChanged['int'].connect(self.sb_subdiv_hori.setValue)
        self.sb_subdiv_hori.valueChanged['int'].connect(self.hsld_subdiv_hori.setValue)
        self.hsld_subdiv_verti.valueChanged['int'].connect(self.sb_subdiv_verti.setValue)
        self.sb_subdiv_verti.valueChanged['int'].connect(self.hsld_subdiv_verti.setValue)
        self.rb_tri.toggled['bool'].connect(self.frame_verti.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoMosaique beta"))
        self.lbl_avance.setText(_translate("MainWindow", "Avancement"))
        self.bt_lancer.setText(_translate("MainWindow", "Lancer"))
        self.rb_rect.setText(_translate("MainWindow", "Rectangle"))
        self.rb_tri.setText(_translate("MainWindow", "Triangle"))
        self.rb_hex.setText(_translate("MainWindow", "Hexagone"))
        self.rb_los.setText(_translate("MainWindow", "Losange"))
        self.lbl_subdiv_verti.setText(_translate("MainWindow", "Subdivision verticale"))
        self.lbl_subdiv_hori.setText(_translate("MainWindow", "Subdivision horizontale"))
        self.bt_ouvrir.setText(_translate("MainWindow", "Ouvrir Image"))
        self.bt_charger.setText(_translate("MainWindow", "Charger base"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuBase_de_donn_e.setTitle(_translate("MainWindow", "Base de donnée"))
        self.menuA_propos.setTitle(_translate("MainWindow", "A propos"))
        self.actionOuvrir_Image.setText(_translate("MainWindow", "Ouvrir Image"))
        self.actionEnregistrer.setText(_translate("MainWindow", "Enregistrer "))
        self.actionEnregistrer_sous.setText(_translate("MainWindow", "Enregistrer sous"))
        self.actionSelectionner_images.setText(_translate("MainWindow", "Selectionner images"))
        self.actionActualiser.setText(_translate("MainWindow", "Actualiser"))
        self.actionLancer.setText(_translate("MainWindow", "Lancer"))

